<Project>
    <ItemGroup Condition="$(UseNugetDLLs)">
        <PackageReference
            Include="Microsoft.Dynamics.BusinessCentral.Development.Tools"
            ExcludeAssets="all"
            GeneratePathProperty="true" />
    </ItemGroup>

    <ItemGroup Condition="$(UseNugetDLLs) and $(TargetFramework) != 'net10.0'">
        <PackageReference Include="System.Collections.Immutable" />
        <PackageReference Include="System.Reflection.Metadata" />
        <PackageReference Include="System.Text.Json" />
    </ItemGroup>

    <PropertyGroup Condition="$(UseNugetDLLs)">
        <NavDLLsDir>$(PkgMicrosoft_Dynamics_BusinessCentral_Development_Tools)/tools/$(TargetFramework)/any/</NavDLLsDir>
    </PropertyGroup>
</Project>