<Project>
    <ItemGroup Condition="$(UseNugetDLLs)">
        <PackageReference
            Include="Microsoft.Dynamics.BusinessCentral.Development.Tools"
            ExcludeAssets="all"
            GeneratePathProperty="true" />
    </ItemGroup>

    <PropertyGroup Condition="$(UseNugetDLLs)">
        <NavDLLsDir>$(PkgMicrosoft_Dynamics_BusinessCentral_Development_Tools)/tools/net10.0/any/</NavDLLsDir>
    </PropertyGroup>
</Project>